#!/bin/bash
# This is the main implementation of the user interfaces and the network functionality

# Declaration of Network variables
HOST=localhost
PORT=1234

#Creation of temporary files
FILE1=/tmp/blkchn-$$
FILE2=/tmp/blkchn-$$
ERROR=/tmp/blkchn-err-$$


# Creation of variable for linking executable file
PROJECT_CHANNEL=project_channel

# Selection of simple dialog or gdialog as per the installed utility
which gdialog 2> /dev/null && DIALOG=gdialog || DIALOG=dialog


# Termination of program
end () {
	rm -f $FILE1 $FILE2 $ERROR $state_file
	exit
	}

# Menu for displaying user
MENU_T="Switching of Channels"
MENU_H="Please choose your channel:"
MENU_1="Regular Channel"
MENU_2="Quantum Encrypted Channel"
MENU_0="Exit"


while true
do

# For the execution of TUI
	if [ `basename $0` = "project_ui" ]
	then
		 printf "Please choose your channel :\n1 - Regular channel\n2 - Quantum Encrypted channel\n0 - Exit\n "
		read INPUT
		
		if [ "$INPUT" = "0" ]
		then
		end
	
		elif [ "$INPUT" = "1" -o "$INPUT" = "2" ]
		then
		echo $INPUT | $PROJECT_CHANNEL 
		printf "\n\nChannel is successfuly switched to : $INPUT\n\n"

		else  
		printf "\n\nInvalid selection! Please select correct channel and try again\n\n"
		fi

# For execution of GUI
	elif [ `basename $0` = "project_gui" ]
	then
		$DIALOG --title "$MENU_T" --menu "$MENU_H" 10 60 2 1 "$MENU_1" 2 "$MENU_2" 2> $FILE1 || end
		INPUT=$(cat $FILE1)

		echo $INPUT | $PROJECT_CHANNEL
		$DIALOG --msgbox "Channel is successfuly switched to : $INPUT" 10 20 


# For exeution of Network features
	elif [ `basename $0` = "project_network" ]
	then
		$DIALOG --title "$MENU_T" --menu "$MENU_H" 10 60 2 1 "$MENU_1" 2 "$MENU_2" 2> $FILE1 || end
		INPUT=$(cat $FILE1)
	
		CHANNEL_CMD="nc $HOST $PORT"
		
		if echo $INPUT | $CHANNEL_CMD
		then $DIALOG --msgbox "Channel is successfuly switched to $INPUT" 10 60
		else
		$DIALOG --msgbox "Error: Server not running" 10 60
		fi
	fi
done
