#!/bin/bash

HOST=localhost
PORT=1234

FILE1=/tmp/blkchn-$$
FILE2=/tmp/blkchn-$$
ERROR=/tmp/blkchn-err-$$
PROJECT_CHANNEL=./project_channel
NCHOSTPORT=`nc $HOST $PORT`
state_file=/tmp/amir-$$
touch $state_file
chmod 777 $state_file

which gdialog 2> /dev/null && DIALOG=gdialog || DIALOG=dialog

end () {
	rm -f $FILE1 $FILE2 $ERROR $state_file
	exit
	}

while true
do

	if [ `basename $0` = "project_ui" ]
	then
		 printf "Please choose your channel :\n1 - Regular channel\n2 - Quantum Encrypted channel\n0 - Exit\n "
		read INPUT

	elif [ `basename $0` = "project_gui" ]
	then
		$DIALOG --inputbox "Please choose your channel :\n1 - Regular channel\n2 - Quantum Encrypted channel\n0 - Exit\n " 10 60 2> $FILE1
		INPUT=$(cat $FILE1)

	elif [ `basename $0` = "project_network" ]
	then
		printf "Please choose your channel :\n1 - Regular channel\n2 - Quantum Encrypted channel\n0 - Exit\n "
		read INPUT
		if [ "$INPUT" = "0" ]
		then 
		end
		fi
		echo $INPUT | $NCHOSTPORT
	
	fi

	if [ `basename $0` = "project_ui" -o `basename $0` = "project_gui" ]
	then


		echo $INPUT | $PROJECT_CHANNEL $state_file
		JSTATE=$(cat $state_file)
		
		if [ "$JSTATE" = "0" ]
		then
		end
	
		elif [ "$JSTATE" = "1" ]
		then
		printf "\n\nChannel is successfuly switched to : $INPUT\n\n"

		elif [ "$JSTATE" = "2" ]
		then 
		printf "\n\nInvalid selection! Please select correct channel and try again\n\n"
		fi

	fi
	
done
