#!/bin/bash
# This is the main implementation of the user interfaces and the network functionality

# Declaration of Network variables
HOST=localhost
PORT=1234

#Creation of temporary files
FILE1=/tmp/blkchn-$$
FILE2=/tmp/blkchn-$$
ERROR=/tmp/blkchn-err-$$

# Creation of variable for linking executable file
PROJECT_CHANNEL=project_channel

# Selection of simple dialog or gdialog as per the installed utility
which gdialog 2> /dev/null && DIALOG=gdialog || DIALOG=dialog


# Termination of program
end () {
	rm -f $FILE1 $FILE2 $ERROR $state_file
	exit
	}

while true
do

# For the execution of TUI
	if [ `basename $0` = "project_ui" ]
	then
		 printf "Please choose your channel :\n1 - Regular channel\n2 - Quantum Encrypted channel\n0 - Exit\n "
		read INPUT
		
		if [ "$INPUT" = "0" ]
		then
		end
	
		elif [ "$INPUT" = "1" -o "$INPUT" = "2" ]
		then
		echo $INPUT | $PROJECT_CHANNEL 
		printf "\n\nChannel is successfuly switched to : $INPUT\n\n" && end

		else  
		printf "\n\nInvalid selection! Please select correct channel and try again\n\n"
		fi

# For execution of GUI
	elif [ `basename $0` = "project_gui" ]
	then
		$DIALOG --inputbox "Please choose your channel :\n1 - Regular channel\n2 - Quantum Encrypted channel\n0 - Exit\n" 10 60 2> $FILE1 || end
		INPUT=$(cat $FILE1)
		
		if [ "$INPUT" = "0" ]
		then
		end
	
		elif [ "$INPUT" = "1" -o "$INPUT" = "2" ]
		then
		echo $INPUT | $PROJECT_CHANNEL
		$DIALOG --msgbox "Channel is successfuly switched to : $INPUT" 10 20 && end

		else
		$DIALOG --msgbox "Invalid selection! Please select correct channel and try again" 20 20
		fi

# For exeution of Network features
	elif [ `basename $0` = "project_network" ]
	then
		$DIALOG --inputbox "Please choose your channel :\n1 - Regular channel\n2 - Quantum Encrypted channel\n0 - Exit\n" 10 60 2> $FILE1 || end
		INPUT=$(cat $FILE1)
	
		CHANNEL_CMD="nc $HOST $PORT"
		if [ "$INPUT" = "0" ]
		then
		end
		
		elif [ "$INPUT" = "1" -o "$INPUT" = "2" ]
		then
		echo $INPUT | $CHANNEL_CMD
		$DIALOG --msgbox "Channel is successfuly switched to $INPUT" 10 60 && end

		else
		$DIALOG --msgbox "Invalid selection! Please select correct channel and try again" 10 60
		fi
	
	fi
done
