#!/bin/bash

FILE1=/tmp/blkchn-$$
FILE2=/tmp/blkchn-$$
ERROR=/tmp/blkchn-err-$$

which gdialog 2> /dev/null && DIALOG=gdialog || DIALOG=dialog

end () {
	rm -f $FILE1 $FILE2 $ERROR
	exit
	}
while true
do
	$DIALOG --inputbox "Which channel would you prefer: " 30 60 2> $FILE1
	INPUT= 'cat $FILE1'
	
