#!/bin/bash
# This is the main implementation of the user interfaces and the network functionality

#Creation of temporary files
FILE1=/tmp/blkchn-$$
FILE2=/tmp/blkchn-$$
ERROR=/tmp/blkchn-err-$$

# Creation of variable for linking executable file
PROJECT_CHANNEL=project_channel

# Selection of simple dialog or gdialog as per the installed utility
which gdialog 2> /dev/null && DIALOG=gdialog || DIALOG=dialog

# Declaring variable for localization
GETTEXT="gettext -d project_ui"

# Menu for displaying user
MENU_T="`$GETTEXT \"Switching of Channels\"`"
MENU_H="`$GETTEXT \"Please choose your channel\"`"
MENU_1="`$GETTEXT \"Regular Channel\"`"
MENU_2="`$GETTEXT \"Quantum Encrypted Channel\"`"
MENU_0="Exit"

# Termination of program
end () {
	rm -f $FILE1 $FILE2 $ERROR $state_file
	exit
	}

while true
do

		$DIALOG --title "$MENU_T" --menu "$MENU_H" 10 60 2 1 "$MENU_1" 2 "$MENU_2" 2> $FILE1 || end
		INPUT=$(cat $FILE1)

		echo $INPUT | $PROJECT_CHANNEL
		$DIALOG --msgbox "`$GETTEXT \"Channel is successfuly switched to :\"` $INPUT" 10 20


done
