#!/bin/bash
# This is the main implementation of the user interfaces and the network functionality

#Creation of temporary files
FILE1=/tmp/blkchn-$$
FILE2=/tmp/blkchn-$$
ERROR=/tmp/blkchn-err-$$

# Creation of variable for linking executable file
PROJECT_CHANNEL=project_channel

# Selection of simple dialog or gdialog as per the installed utility
which gdialog 2> /dev/null && DIALOG=gdialog || DIALOG=dialog

# Declaring variable for localization
GETTEXT="gettext -d project_ui"

# Termination of program
end () {
	rm -f $FILE1 $FILE2 $ERROR $state_file
	exit
	}

while true
do

		$DIALOG --inputbox "`$GETTEXT \"Please choose your channel :\"`\\n`$GETTEXT \"1 - Regular channel\"`\\n`$GETTEXT \"2 - Quantum Encrypted channel\"`\\n`$GETTEXT \"0 - Exit\"`\\n" 10 60 2> $FILE1 || end
		INPUT=$(cat $FILE1)
		
		if [ "$INPUT" = "0" ]
		then
		end
	
		elif [ "$INPUT" = "1" -o "$INPUT" = "2" ]
		then
		echo $INPUT | $PROJECT_CHANNEL
		$DIALOG --msgbox "`$GETTEXT \"Channel is successfuly switched to :\"` $INPUT" 10 20 && end

		else
		$DIALOG --msgbox "`$GETTEXT \"Invalid selection! Please select correct channel and try again\"`" 20 20
		fi

done
